cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
      dir: ${AWS_S3_DIR_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false